// Copyright (c) 2024-2025 Traian Avram. All rights reserved.

#pragma once

/**
 * PLATFORM MACROS.
 */

#ifndef SE_PLATFORM_WIN64
    #define SE_PLATFORM_WIN64 0
#endif // SE_PLATFORM_WIN64

/**
 * BUILD CONFIGURATION MACROS.
 */

#ifndef SE_CONFIGURATION_EDITOR_DEBUG
    #define SE_CONFIGURATION_EDITOR_DEBUG       0
#endif // SE_CONFIGURATION_EDITOR_DEBUG

#ifndef SE_CONFIGURATION_EDITOR_DEVELOPMENT
    #define SE_CONFIGURATION_EDITOR_DEVELOPMENT 0
#endif // SE_CONFIGURATION_EDITOR_DEVELOPMENT

#ifndef SE_CONFIGURATION_GAME_DEBUG
    #define SE_CONFIGURATION_GAME_DEBUG         0
#endif // SE_CONFIGURATION_GAME_DEBUG

#ifndef SE_CONFIGURATION_GAME_DEVELOPMENT
    #define SE_CONFIGURATION_GAME_DEVELOPMENT   0
#endif // SE_CONFIGURATION_GAME_DEVELOPMENT

#ifndef SE_CONFIGURATION_GAME_SHIPPING
    #define SE_CONFIGURATION_GAME_SHIPPING      0
#endif // SE_CONFIGURATION_GAME_SHIPPING

/* Target macros. */
#define SE_TARGET_EDITOR (SE_CONFIGURATION_EDITOR_DEBUG || SE_CONFIGURATION_EDITOR_DEVELOPMENT)
#define SE_TARGET_GAME   (SE_CONFIGURATION_GAME_DEBUG   || SE_CONFIGURATION_GAME_DEVELOPMENT || SE_CONFIGURATION_GAME_SHIPPING)

/* Configuration macros. */
#define SE_CONFIGURATION_DEBUG       (SE_CONFIGURATION_EDITOR_DEBUG       || SE_CONFIGURATION_GAME_DEBUG)
#define SE_CONFIGURATION_DEVELOPMENT (SE_CONFIGURATION_EDITOR_DEVELOPMENT || SE_CONFIGURATION_GAME_DEVELOPMENT)
#define SE_CONFIGURATION_SHIPPING    (SE_CONFIGURATION_GAME_SHIPPING)

/**
 * SHARED LIBRARY API SPECIFIERS.
 */

#if SE_PLATFORM_WIN64
    #define SE_API_SPECIFIER_EXPORT __declspec(dllexport)
    #define SE_API_SPECIFIER_IMPORT __declspec(dllimport)
#else
    #define SE_API_SPECIFIER_EXPORT
    #define SE_API_SPECIFIER_IMPORT
#endif // SE_PLATFORM_WIN64

#if SE_TARGET_EDITOR
    #ifdef SE_PROJECT_RUNTIME
        #define SHOOTER_API SE_API_SPECIFIER_EXPORT
    #else
        #define SHOOTER_API SE_API_SPECIFIER_IMPORT
    #endif // SE_PROJECT_RUNTIME
#else
    #define SHOOTER_API
#endif // SE_TARGET_EDITOR

/**
 * GENERAL-PURPOSE, PLATFORM AGNOSTIC, MACROS.
 */

#define FORCEINLINE            __forceinline
#define SE_PLATFORM_DEBUGBREAK __debugbreak()
#define SE_FUNCTION            __FUNCSIG__

#define NODISCARD    [[nodiscard]]
#define MAYBE_UNUSED [[maybe_unused]]
#define LIKELY       [[likely]]
#define UNLIKELY     [[unlikely]]
